# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry

version: '2'
services:
  ckan:
    container_name: ckan
    image: ckan
    build: ../.
    depends_on:
      - db
      - solr
      - redis
      - pusher
      - postfix
    links:
       - db
       - solr
       - redis
       - pusher
       - postfix
    ports:
       - "5000:5000"
    environment:
       CKAN_DATASTORE_WRITE: "postgresql://ckan:ckan@db:5432/datastore_default"
       CKAN_DATASTORE_READ: "postgresql://datastore_default:datastore@db:5432/datastore_default"
       CKAN_PUSHER_URL: "http://pusher:8800"
       CKAN_REDIS_URL: "redis://redis:6379/0"
       CKAN_SITE_URL: "http://vocol.kbs.uni-hannover.de:5000"
       CKAN_SOLR_URL: "http://solr:8983/solr/ckan"
       CKAN_SQLALCHEMY_URL: "postgresql://ckan:ckan@db:5432/ckan"
    #volumes:
       # - ./ckan-entrypoint.sh:/ckan-entrypoint.sh 
       #- ../Plugins/ckanext-TIBtheme:/usr/lib/ckan/default/src/ckanext-TIBtheme
       # - ../Plugins/ckanext-SPARQLWrapper:/usr/lib/ckan/default/src/ckanext-SPARQLWrapper
       # - ../Plugins/ckanext-videoviewer:/usr/lib/ckan/default/src/ckanext-videoviewer
  db:
    build: ./postgresql-loaded/
    container_name: db
    image: postgresql:loaded
  solr:
    build: ./solr/
    container_name: solr
    image: fhg/solr
  redis:
    container_name: redis
    image: redis
  pusher:
    container_name: pusher
    image: easyckan/ckan-datapusher:2.6
  postfix:
    container_name: postfix
    image: tozd/postfix
    ports:
      - "25:25"
    environment:
       MY_NETWORKS: "172.18.0.0/16 127.0.0.0/8"
